name: vtalk_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^13.2.0
  provider: ^6.1.1
  http: ^1.2.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  flutter_secure_storage: ^9.0.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  flutter_v2ray: ^1.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo_bnb.png
  android_12:
    image: assets/images/logo_bnb.png
    color: "#FFFFFF"
  fullscreen: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/